# Generated by Django 2.2.2 on 2019-06-28 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190628_2033'),
        ('imoveis', '0013_auto_20190622_1903'),
        ('alugados', '0002_auto_20190628_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alugados',
            name='fk_cliente',
        ),
        migrations.RemoveField(
            model_name='alugados',
            name='fk_imovel',
        ),
        migrations.AddField(
            model_name='alugados',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_alugados', to='clientes.Clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alugados',
            name='imovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_alugados', to='imoveis.Imoveis'),
            preserve_default=False,
        ),
    ]
