# Generated by Django 2.2.2 on 2019-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imoveis',
            old_name='sobrenome',
            new_name='Rua',
        ),
        migrations.RemoveField(
            model_name='imoveis',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='imoveis',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='imoveis',
            name='nome',
        ),
        migrations.AddField(
            model_name='imoveis',
            name='Cidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='Numero',
            field=models.DateField(blank=True, null=True, verbose_name='Numero do imóvel'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
    ]
