# Generated by Django 2.2.2 on 2019-06-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_auto_20190622_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imoveis',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='imoveis',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='imoveis',
            old_name='Rua',
            new_name='rua',
        ),
    ]
