# Generated by Django 2.2.2 on 2019-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_auto_20190622_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='numero',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Numero do imóvel'),
        ),
    ]
