# Generated by Django 2.2.2 on 2019-06-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_auto_20190622_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imoveis',
            name='numero',
        ),
    ]
