# Generated by Django 2.2.2 on 2019-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_remove_imoveis_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero do imóvel'),
        ),
    ]
