# Generated by Django 2.2.2 on 2019-06-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_remove_imoveis_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='numero',
            field=models.DateField(blank=True, null=True, verbose_name='Numero do imóvel'),
        ),
    ]
