# Generated by Django 2.2.2 on 2019-06-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_imoveis_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imoveis',
            name='numero',
        ),
    ]
