# Generated by Django 2.2.2 on 2019-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_remove_imoveis_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
