# Generated by Django 2.2.2 on 2019-06-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0012_imoveis_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número do imóvel'),
        ),
    ]
