# Generated by Django 2.2.2 on 2019-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=30, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
