# Generated by Django 2.2.2 on 2019-06-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190622_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(default=1, max_length=30, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
